title: Memos
description: Iâ€™m not a JavaScript fan, but needs must.
author: Brahim MACHKOURI  
baseurl: /minimal-blog-for-github-pages
timezone: Europe/Paris
# social links
#twitter_username: thesubmarine # DO NOT include the @ character, or else the build will fail!
github_username:  brahimmachkouri # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
show_tags: false # set to false to remove tags on the homepage
plugins:
  - jemoji
